### ISSUE TITLE
fix POST /messages response body, invalid JSON

### ISSUE THREAD

**Issue by mknunez15** [theotw/natssync#39]
POST /messages response body error: 
"{\"source\":\"urn:theotw:astra:echolet\",\"type\":\"natssync-sb.*.echo\",\"specversion\":\"1.0\",\"id\":\"5f7a9b7d-b665-43bb-bdbb-36dab410fb76\",\"data\":\"20210520-23:57:36.305 | echoproxylet * hello Argo\"}\n"
![Screen Shot 2021-05-21 at 1 00 12 PM](https://user-images.githubusercontent.com/45438733/119185828-835e6780-ba34-11eb-9d14-e46ea7b72215.png)

should not be escape characters (back slash), "\n" in json payload

**Comment by bmason42** [comment]
Yep, encoding issue there.  Its fixed now. Grab the latest
